
				// Mark all triangles generated by this contour
				// as having the area cont.area
				for (int j = 0; j < ntris; areaIndex++, j++) {
					areas[areaIndex] = cont.area;
				}

				for (int j = 0; j < ntris; regIndex++, j++) {
					regs[regIndex] = cont.reg;
				}
